import Card from '@/components/Card'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  //price, age, km, description, location

  const cardInfo = [
    {
      price: 50000,
      age: '2018',
      km: 45.000,
      description: 'Hyundai Tucson Gls',
      location: 'Barquisimeto - Lara'
    }
  ]

  return (
    <div className={styles.app}>
      <Head>
        <title>Carros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {cardInfo.map(info => <Card {...info} />)}
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
