import Navbar from '@/components/Navbar'
import PrimaryButton from '@/components/Primarybutton'
import Error from 'next/error'
import Head from 'next/head'
import Image from 'next/image'

/*
    {
    "name": "Toyota Corolla",
    "description": "Toyota negro",
    "price": 500000,
    "age": "2018",
    "km": 320000,
    "location": "Miranda, Caracas",
    "more": "Bien cuidado",
    "image": "https://http2.mlstatic.com/D_NQ_NP_939992-MLV51901323738_102022-O.webp"
    }
*/

export default function CarDetail({ car, error }) {

    const { name, description, price, age, km, location, more, image } = car

    if (error && error.statusCode) return <Error statusCode={error.statusCode} title={error.statusText} />

    return (
        <div>

            <Head>
                <title>{name}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />
            <div className='flex justify-center '>
                <div className='w-[100rem] min-h-[50rem] bg-[#e3f6f5] mx-4 p-9 rounded-xl flex gap-x-2'>
                    <div className=' h-full'>
                        <div className='h-[31.25rem] w-[43.75rem] relative'>
                            <Image src={image} alt="carro" height='100%' width='100%' layout='fill' className='rounded-lg' />
                        </div>
                        <div className=' w-full h-fit flex gap-3 flex-col py-2 justify-around'>
                            <h1 className='text-[2rem] font-semibold'>{name}</h1>
                            <span className='text-m '>{age} | {km}km</span>
                            <h1 className='text-[2rem] font-medium'>${price}</h1>
                            <div>
                                <PrimaryButton text={'Consultar'} />
                            </div>
                        </div>
                    </div>
                    <div className='outline outline-1 outline-gray-400'></div>
                    <div className='w-[68.75rem] border-2 border-green-500'>
                        <div>
                            <h1></h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export async function getServerSideProps({ query: { id } }) {

    const res = await fetch(`http://localhost:3000/api/cars/${id}`)

    if (res.status === 200) {
        const car = await res.json()
        return {
            props: { car }
        }
    }

    return {
        props: {
            error: {
                statusCode: res.status,
                statusText: 'Invalid ID'
            }
        }
    }
}